theme: jekyll-theme-minimal
title: 2022 Practical Workshop
url: "https://symgenoevolab.github.io/practical_workshop_2022/"
markdown: kramdown
description: 2022 NSYSU-AS Bioinformatics Practical Workshop
